af_threshold: 0.001
consequence_filter: missense_variant
domains:
  extracellular_domain:
  - 23
  - 233
  intracellular_loop:
  - 316
  - 466
  m1:
  - 234
  - 254
  m2:
  - 259
  - 279
  m3:
  - 292
  - 315
  m4:
  - 467
  - 489
  signal_peptide:
  - 1
  - 22
gene_symbol: CHRNA7
genome_build: GRCh38
log_dir: logs
output_dir: data/processed
